### ISSUE TITLE
Json payload instead of URL parameters

### ISSUE THREAD

**Issue by twoxfh** [huilam/jsoncrudrest#1]
It seems the URL parameters could get very long and browsers have different max lenghts, any thought to passing the parameters in a Json document instead? Then you could have a Json schema validate the parameters. The schema may look something like below. Thoughts?

{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "title":"Sample Where Query Schema for JSON config file",
   "description":"Validates String, Number, Date, NumberIDs, StringIDs",

   "type": "object",
   "properties": {
     "where": {
       "type": "object",
       "properties": {
         "field1": { "$ref": "#/definitions/string"},
         "field2": { "$ref": "#/definitions/number" },
         "field3": { "$ref": "#/definitions/date" },
         "field4": { "$ref": "#/definitions/numberid" },
         "field5": { "$ref": "#/definitions/stringid" }
       },
    "anyOf": [
        {"required": ["field1"]},
        {"required": ["field2"]},
        {"required": ["field3"]},
        {"required": ["field4"]},
        {"required": ["field5"]}
    ]
     },
"order":{
  "type":"object",
  "properties":{
       "type":{ "type": "string",
           "enum": ["ASC","DESC"]},

  "fields":{
 "type": "array",
 "maxItems": 2,
 "items": {
           "type": "string",
           "enum": ["field1","field2","field3","field4","field5"]
          },
  
       "required": ["items"]
     }},
       "required": ["type", "fields"]
},

     "limit":{"enum":[10,20,50],"type":"number","default": "10"},
	 "page":{"type":"number","minimum": 0,
            "maximum": 999,"default": "0"}
   },
       "required": ["where", "limit","page"]
    ,
   "definitions": {
     "string": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["=","like"] },
         "value": { "type": "string",
         "maxLength": 10,
         "minLength": 1,
         "pattern": "^[a-zA-Z0-9]+$"}
       },
       "required": ["operator", "value"]
     },
      "number": {
       "type": "object",
       "properties": {
         "operator": {"enum": [">","<","="] },
         "value": { "type": "number",
            "minimum": 0,
            "maximum": 999999999999 }
       },
       "required": ["operator", "value"]
     },
      "numberid": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["in"] },
              "value": {
 "type": "array",
 "maxItems": 20,
 "items": {
           "type": "number",
           "minimum": 0,
            "maximum": 9999999999
          },
  
       "required": ["items"]
     }
       },
       "required": ["operator", "value"]
     },
      "stringid": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["in"] },
              "value": {
 "type": "array",
 "maxItems": 20,
 "items": {
           "type": "string",
         "maxLength": 10,
         "minLength": 1,
         "pattern": "^[a-zA-Z0-9]+$"
          },
  
       "required": ["items"]
     }
       },
       "required": ["operator", "value"]
     },
      "date": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["between"], "maxDays":"365" },
         "value": { "type": "string", "format": "date-time"},
         "value2": { "type": "string", "format": "date-time" }

       },
       "required": ["operator", "value", "value2"]
     }
   }
}

**Comment by huilam** [comment]
I believe you referring filtering, orders etc, currently jsoncrudrest trying to make thing simple. Having json format to do all these might be too complicated for many people. Need more thinking.
